OBJS_MAIN +=\
_gen/objs/cmdoptios/cmd/cmdline.o \
_gen/objs/cmdoptios/probar/procbar.o \
_gen/objs/cmdoptios/version/versioninfo.o \
_gen/objs/common/commlib/common.o \
_gen/objs/common/swshlibtest/swshobjtest.o \
_gen/objs/iniconfig/inilib/dictionary.o \
_gen/objs/iniconfig/inilib/iniparser.o \
_gen/objs/logger/loglib/logger.o \
_gen/objs/generator/GACbin/check_type.o \
_gen/objs/generator/GACbin/copy_format.o \
_gen/objs/generator/GACbin/fill_range.o \
_gen/objs/generator/GACbin/genbin.o \
_gen/objs/generator/GACbin/get_tail.o \
_gen/objs/generator/GACbin/patch_head.o \
_gen/objs/generator/GACbin/set.o \
_gen/objs/generator/GACbin/set_hex_buffer.o \
_gen/objs/generator/GACbin/set_hex_name.o \
_gen/objs/generator/GACgen/GACGenerate.o \
_gen/objs/hex/align/align.o \
_gen/objs/hex/block/blockhex.o \
_gen/objs/hex/fill/cathex.o \
_gen/objs/hex/fill/crchex.o \
_gen/objs/hex/fill/fillhex.o \
_gen/objs/hex/gen/createhexlist.o \
_gen/objs/hex/gen/genhexfile.o \
_gen/objs/hex/operate/ophex.o \
_gen/objs/hex/readinfo/readhex.o \
_gen/objs/hex/readinfo/readini.o \
_gen/objs/hex/readinfo/readranges.o \
_gen/objs/GACmain/main/GACheadinfo.o \
_gen/objs/GACmain/main/GACmain.o \
_gen/objs/testcpp/test/123.o \

